# Generated by Django 5.2 on 2025-05-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_timeoffrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='hire_date',
        ),
    ]
